### ISSUE TITLE
Inventory: salvage all <rarity> only selects one item at a time

### ISSUE THREAD

**Issue by forrester-marc** [gwdevhub/GWToolboxpp#1001]
The list of items to salvage does populate with the correct rarity and the salvage operation is successful but it never populates the list with more than one item or stack.  identify all <rarity> is working normally, this is only a problem with salvage kits.

**Comment by 3vcloud** [comment]
This is a gwca issue that bleeds into toolbox, there is no bag_id on the bag struct, or it means something else now - gwca item def needs revisiting to use the index property for this stuff instead.

**Comment by forrester-marc** [comment]
wow that seems like a hell of a scructural change to be making twenty years after launch - good luck working on this shifting terrain!

**Comment by DubbleClick** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/10667051ba2d016d8b82381213ec71f05d25e0a1
