### ISSUE TITLE
Items will not move to Xunlai Chest with ctrl + left click.

### ISSUE THREAD

**Issue by BearsMan** [gwdevhub/GWToolboxpp#1004]
<img width="59" alt="image" src="https://github.com/gwdevhub/GWToolboxpp/assets/34116754/9401ef4a-09e8-4447-b529-c9d94dec7be9">
Hello, I discovered an issue when trying to move Jadite Shards or any other item to the Xunlai chest with a ctrl + click when trying to move it to the chest via a hotkey.

**Comment by 3vcloud** [comment]
what hotkey?

**Comment by DubbleClick** [comment]
Ctrl + Left Click.

**Comment by BearsMan** [comment]
CTRL + left click is what I am using to move items to chest.

**Comment by 3vcloud** [comment]
Check available storage

**Comment by BearsMan** [comment]
I will get back to you on that.

**Comment by BearsMan** [comment]
Okay. I got it, normally, when you put anything into the chest, you don't have to go into an open tab slot. You can ctrl + click and it will automatically go into the slot. 
<img width="171" alt="image" src="https://github.com/gwdevhub/GWToolboxpp/assets/34116754/aa9b6000-2592-4eb3-9989-bde3339335e0">
I added 6 shards into my chest, but I never had to find what number slot it was in. It would just do it without me finding which tab it is in.

**Comment by BearsMan** [comment]
I was able to replicate it and fix it so I will close this.
