### ISSUE TITLE
CTRL+Click Material Logic not working.

### ISSUE THREAD

**Issue by Spectarz** [gwdevhub/GWToolboxpp#1006]
if material pane is full of item it doesn't move it to current open storage pane.

**Comment by BearsMan** [comment]
I was able to replicate it on my alt account easily, however, it may be buggy because I wasn't having that after my fix.

**Comment by Spectarz** [comment]
what was the fix? I will read your post.

**Comment by BearsMan** [comment]
On another 3 accounts that I have, I was able to test the logic again and it worked.

**Comment by Spectarz** [comment]
Non-material items work fine according to the storage logic selection for me. But I can't get materials to follow the unchecked logic option.  Basically first move into materials pane, if full move to open storage pane.

**Comment by BearsMan** [comment]
Yeah, that one I figured out after I tested it from my main account and then tested my alt accounts. I did discover that non-material stuff movements were fine. Then I checked the material lists and it was fine after, the only thing that I can think of is when the chest in full of items, you either have to delete something that isn't needed or check a different panel number.
