### ISSUE TITLE
Draw all quests (minimap, symbol renderer) problems:

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1017]
ticking it makes no quest markers drawn at all
![image](https://github.com/gwdevhub/GWToolboxpp/assets/7896469/7efaeddd-3dcd-46fa-9995-59dd65668a94)

even if it's unticked, quests are cycled through, but don't cycle back, so the active quest changes every time you zone.

**Comment by 3vcloud** [comment]
Check how this behaves with this setting too 
![image](https://github.com/gwdevhub/GWToolboxpp/assets/10796356/d01e383b-e599-4db9-8edf-a7eb41e7df10)

**Comment by DubbleClick** [comment]
Edit: drawing of multiple markers does actually seem to work. Just wasn't getting one on any of the 4 quests there, for some reason,

**Comment by DubbleClick** [comment]
![image](https://github.com/gwdevhub/GWToolboxpp/assets/7896469/f3c81c0f-be78-4929-b873-b309c78cbdea)
when this setting is on, the active gw quest marker should be skipped, otherwise you get a double draw on it 
![image](https://github.com/gwdevhub/GWToolboxpp/assets/7896469/1031dff6-0a01-48d9-aeda-fddca864a7d4)

**Comment by adituv** [comment]
> even if it's unticked, quests are cycled through, but don't cycle back, so the active quest changes every time you zone.

I couldn't reproduce this.  Checking the commit history, I removed the cycling active quests workaround in December so it isn't this feature causing it.  I therefore also couldn't check the interaction with the "keep current quest" game option.

For the improvements and maybe moving the setting, I'll leave that up to you two and your judgement.

**Comment by 3vcloud** [comment]
I think we should shelve this feature, its just very useful in practice and has a lot of edge cases

**Comment by DubbleClick** [comment]
I don't think we should. It's really cool and useful when done right, so unless it's technical difficulties preventing it, I'll have a look into it when I get more free time. Can leave it as it is, except that we have to figure out what causes the quest switching.
