### ISSUE TITLE
Extend alias feature in chat settings to allow multiple chat commands per alias

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#1020]
i.e. an alias created as "hi" could send "!Hello there :)" and "/wave" when activated

**Comment by mhpcc** [comment]
so the user would have... multiple (infinite?) fields?

i.e.
```
Command Alias1 Alias2 ... AliasN
"hi "/wave" "hello there" ... "heyo"
```

or do you mean
```
"hi" "/wave"
"hi" "hello there"
"hi" ...
"hi" "heyo"
```

**Comment by DubbleClick** [comment]
so the user would have... multiple (infinite?) fields?

i.e.

Command Alias1 Alias2 ... AliasN
"hi "/wave" "hello there" ... "heyo"
or do you mean

"hi" "/wave"
"hi" "hello there"
"hi" ...
"hi" "heyo"
