### ISSUE TITLE
Plugins that call GW::Initialize crash on TB 6.16

### ISSUE THREAD

**Issue by JaborGW** [gwdevhub/GWToolboxpp#1024]
If a plugin calls `GW::Initialize`, it will crash when toolbox is closed (directly or when guild wars is closed). I added a minimal plugin for testing here https://github.com/JaborGW/GWToolboxpp/commit/ad984d29b60c7134fa0e2e814ece5020c203cd52

The same plugin does not crash on toolbox 6.12 (with the signature update from https://github.com/gwdevhub/GWCA/commit/7cda654e7b92a45ab2cd4d7997baaf1dd9e01b21 cherry-picked).

**Comment by DubbleClick** [comment]
issue somewhere in gwca then, possibly related to the rework. Can leave this open here, though.

**Comment by AlexMacocian** [comment]
I'm able to replicate it. When you close toolbox, it doesn't crash Guild Wars executable or doesn't throw anywhere, it simply destroys the API.

So probably it's somewhere in GWCA in Terminate or DisableHooks

**Comment by 3vcloud** [comment]
Issue was related to trying to terminate GWCA when inside the game loop
