### ISSUE TITLE
Plugin chat commands not triggered by tb hotkeys

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1025]
Can I trigger a command I created with a plugin, with a hotkey ? For instance I created the /dosomething command, working well when I manually type in the chat, but does nothing when triggered with the hotkey "chat command" 😦

from discord

**Comment by 3vcloud** [comment]
@DubbleClick to test this when able

**Comment by DubbleClick** [comment]
not fixed, when a hotkey triggers a chat command the plugin still doesn't receive it
