### ISSUE TITLE
Traveling to a pvp outpost while having cursor over a toolbox window blocks left click input until you go back to a pve outpost

### ISSUE THREAD

**Issue by Rumpower** [gwdevhub/GWToolboxpp#1027]
Using the Travel window to teleport to a PvP outpost or hovering over a toolbox window while using the /tp command to do the same results in the game not responding to your left click input. The world map does still work.

Right click still works, so you can move the camera and spin your character around in the inventory window, but almost everything requiring a left click stops working.

The issue persists until you go back to a pve outpost. Going to character select and logging in to the same character or another character that's also in a PvP area doesn't resolve it either.

**Comment by BearsMan** [comment]
Toolbox is disabled in PvP areas now. Check the release notes.

**Comment by 3vcloud** [comment]
Yep, already checked for wndproc signals through that button and we get none (or if we do its too late)

**Comment by DubbleClick** [comment]
yeh we manually send one in the top right buttons hook
we could refactor the hook to GWToolbox since it's not actually related to GameSettings and enable it there again
