### ISSUE TITLE
minimap drawing is choppy

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1029]
https://cdn.discordapp.com/attachments/1231601552687632464/1231601786754826350/image.png?ex=66378d8c&is=6625188c&hm=8f66af9583f7c1a8cee25e925935e11df5fc099122baa8e0da86141216eacd57&

Pictures aren't the best example, but TB minimap drawing seems to have a longer input frequency between dot connections causing choppier curved lines compared to previous versions. Can I assume it is something I have to just live with?

From discord

**Comment by adituv** [comment]
Possibly already fixed?  https://github.com/gwdevhub/GWToolboxpp/commit/f9cccb776805a7d2356114ab9c99d483761144a4
