### ISSUE TITLE
Mini-map Quest Marker Draws multiple times.

### ISSUE THREAD

**Issue by BearsMan** [gwdevhub/GWToolboxpp#1030]
<img width="409" alt="image" src="https://github.com/gwdevhub/GWToolboxpp/assets/34116754/a0dd0a93-ad83-40fb-a231-a327526c6e9a">

While doing Bogroots, I noticed that the quest marker draws more than once. even if you only have 1 quest shown in the log. It could related to a pending release that is fixed, but I just wanted to be sure. So I added an issue here.

**Comment by BearsMan** [comment]
If this is not needed, then we can close.

**Comment by DubbleClick** [comment]
I assume you have draw all quests ticked on (Minimap, Symbolrenderer). Please send a new screenshot with your quest log and tb settings open.

**Comment by BearsMan** [comment]
> I assume you have draw all quests ticked on (Minimap, Symbolrenderer). Please send a new screenshot with your quest log and tb settings open.

Yes, I do. I'll take another screenshot with the log and setting open when I get back.

**Comment by BearsMan** [comment]
> I assume you have drawn all quests ticked on (Minimap, Symbolrenderer). Please send a new screenshot with your quest log and TB settings open.

Here you go: https://imgur.com/xqWjt8S

I noticed this is closed, but I will assume that is pending in a new release. This is just a comment here for the picture requested.

**Comment by 3vcloud** [comment]
Problem between chair and keyboard

**Comment by DubbleClick** [comment]
There is no problem here, the functionality works exactly as expected.

You have multiple quests. What do you think does "draw all questmarkers" do? It draws all markers for your quests.
