### ISSUE TITLE
Real time timer resets despite "never reset" setting

### ISSUE THREAD

**Issue by adituv** [gwdevhub/GWToolboxpp#1031]
Title.  Apparently the timer resets when exiting an outpost.  I'm not sure exactly what the intended behaviour is here, though.

![image](https://github.com/gwdevhub/GWToolboxpp/assets/1254246/19f9f6f5-4b2d-4626-885f-0f22d278b539)

**Comment by Dejuve** [comment]
Here's a recording of the issue: [here](https://youtu.be/XJw41hwmPT0) (It's still pending/processing at the time of submitting this)
