### ISSUE TITLE
Change gwca GetIsAgentTargettable to allow targetting signposts with a name tag

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1034]
https://github.com/gwdevhub/GWToolboxpp/commit/b3c91ee831c73a427be683b5afe4713a589f121e

revert this in the process

**Comment by DubbleClick** [comment]
if you think the gwca commit is enough then tag this pending release.
I thought about it and only allowing to target locked chests with ctrl + click still makes sense, I haven't found a situation where I would want to target another gadget over the minimap

**Comment by 3vcloud** [comment]
Nope, this should reflect gameplay not special cases
