### ISSUE TITLE
npc_to_find should be able to find real players

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1036]
/target Realplayername

**Comment by DubbleClick** [comment]
err, it is able to, you just need to specify "player" in the target command.

**Comment by 3vcloud** [comment]
I think I had stuff like "I want to easily find the merchant without having to reorient myself when entering an outpost", so targetting by player name wasn't really a scenario I would consider for a chat command. I still don't tbh but I don't see any harm in opening it up to player names

**Comment by DubbleClick** [comment]
My main thought here is that nobody wants to remember to `/target player jonsnow` when `/target tolk` is enough to target a merchant.
