### ISSUE TITLE
/highlight to change color/size/shape of an enemy or teammember until reset by the user

### ISSUE THREAD

**Issue by Zane1-2** [gwdevhub/GWToolboxpp#1038]
/highlight to change color/size/shape of an enemy or teammember until reset by the user

**Comment by BearsMan** [comment]
I know that /marktarget is there because @backtwobaysix had it added a few versions back.

**Comment by DubbleClick** [comment]
> I didn't find any customization options in the current version

we can't really prioritize that to the next release and will close the issue here - please open a new one if cusomization options are something you want
