### ISSUE TITLE
Armory: Missing Paragon armor

### ISSUE THREAD

**Issue by wokestrom** [gwdevhub/GWToolboxpp#1043]
The Deldrimor armor for Paragon (Winged Raiment, Sashed Leggings, Banded Sandals) is missing in the armory.

**Comment by DubbleClick** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/b75cdd9801ee13f35e15eae1d58132aaff97653d#diff-5ffb5b7d6ed42e7fcccdb7d55bf99e2e19b011fa644e1860588f0890a017e3dbR1347-R1349
