### ISSUE TITLE
GW on Wine: Impaired Movement

### ISSUE THREAD

**Issue by nilswende** [gwdevhub/GWToolboxpp#1044]
Hi,

I'm playing GW via Wine on Linux.

When I start the toolbox, while right-click-holding to change the view direction, my character won't respond to WASD movement commands. Only when I stop moving the mouse can I use the WASD keys.
Right click does not need to be released for WASD to work again, just the mouse movement needs to stop.

The problem persists even when i close the toolbox again.

I realize GW is a Windows game and you don't really support Linux, but maybe someone has an idea anyways.

**Comment by FelixGrafschmidt** [comment]
This is obviously anecdotal, but I had similar issues with multiple games on Linux in the past (Guild Wars, FFXIV). I was able to track it down to this: https://www.reddit.com/r/linux_gaming/comments/ompubz/question_to_ffxiv_linuxusers/.
If I remember correctly, the solution in GW was to change the windowed/fullscreen option though I do not remember what the solution was at the end.

**Comment by nilswende** [comment]
Thanks for suggesting this, I actually am on windowed fullscreen.

I auto-updated from v6.16 (most likely) to 6.22 today and it now seems to work correctly. Fingers crossed it stays that way.
