### ISSUE TITLE
 hide_city_pcons_in_explorable_areas setting gets ignored on launch and defaults to = false

### ISSUE THREAD

**Issue by Rumpower** [gwdevhub/GWToolboxpp#1047]
the 
> hide_city_pcons_in_explorable_areas = true

setting/toggle gets ignored when launching toolbox

if the box is ticked in settings it will properly save and load as = true, but defaults to = false when launching toolbox.

someone on the discord mentioned  

> it's missing from the LoadSettings method in pconswindow so should be an easy fix

**Comment by adituv** [comment]
Sorry, I forgot to also mention on the discord that I already submitted the fix, and it will be included in the next toolbox release.  Thanks for reporting it!
