### ISSUE TITLE
Add sell value to runes/insignas

### ISSUE THREAD

**Issue by JimRaynerd** [gwdevhub/GWToolboxpp#1049]
The latest update added the value of runes/insignas to items in your inventory which is a big QOL feature. 
The value shown is the buy value. It would be nice to add the sell value as well. So you'd end up with [name of rune]: B: [buy value] S: [sell value] . Here's what I mean

![Buy_sell_runes](https://github.com/gwdevhub/GWToolboxpp/assets/168713400/d73d7a6d-1538-49b0-b33d-62bcdcfaa274)

**Comment by 3vcloud** [comment]
Values are fetched from kamadan trade website, currently only buy value is available
