### ISSUE TITLE
Add notification on ítem with maximum rolls

### ISSUE THREAD

**Issue by apoguita** [gwdevhub/GWToolboxpp#1050]
a suggestion for the module that fetch prices on ítem components, for the components that dont trade on merchant,  add a notification if the ítem has one or more maximum rolls on mods son its easier and quicker to identify valuables

![IMG_20240502_073510](https://github.com/gwdevhub/GWToolboxpp/assets/77995928/b9f881bb-4098-4f18-b3f2-118c54e03d5b)

this ítem has 2 max roll mods and the dmg mod is not max(min?) roll

**Comment by 3vcloud** [comment]
Unless mods have obscure max stats, this would just add chaff to the tooltip rather than new info

**Comment by apoguita** [comment]
the idea proposed, is intended for both New and old players. 

New players dont know the mayority of mods that exists or their values, this game only value perfect mods, a 20% enchant is soight for, a 19% enchant is not.

for veteran players , it adds a really nice and Quick way of selecting loot for salvanging/ vendoring / stashing

referring to the pictured attached, that weapon does no have any modifier that has vendo rvale, therefore, theres no extra clutter on the UI.

the same ares used for displaying rune and insignia values, could be used to indicaste if one of your mods has a máx value roll, in the case of the picture attached, it is 20/20 sundering and also 20% enchant.
