### ISSUE TITLE
Revert outgoing whisper color

### ISSUE THREAD

**Issue by RiftLurker** [gwdevhub/GWToolboxpp#1058]
With a recent change the outgoing whisper messages are now blue, please give us an option to revert back to the green color.

**Comment by 3vcloud** [comment]
can't replicate this

**Comment by DubbleClick** [comment]
you're on an old version

**Comment by DubbleClick** [comment]
or specifically turned the setting on, which I doubt.

https://github.com/gwdevhub/GWToolboxpp/commit/ce9dbcf82b4289be081a49dda197ecb2e7ed0ed2

**Comment by RiftLurker** [comment]
It was indeed turned on for some reason
