### ISSUE TITLE
Fetch prices for item components always on

### ISSUE THREAD

**Issue by chang-gw** [gwdevhub/GWToolboxpp#1059]
![gw280](https://github.com/gwdevhub/GWToolboxpp/assets/165207702/b332b79f-d7ba-482b-86be-b2e2facdd82c)
Despite the "Fetch prices for item components" option being unticked, the feature is always turned on.

**Comment by AlexMacocian** [comment]
Ah yes sorry I can repro this. I'll make a fix for it tomorrow
