### ISSUE TITLE
Get modelID for non living agents

### ISSUE THREAD

**Issue by JimRaynerd** [gwdevhub/GWToolboxpp#1074]
Currently you can change colors on all living agents on the minimap as the info tab pulls their model ID which is needed to make said change.

But if you want to change ID on things like chests, there's no model ID pulled and thus not change of color is possible. 

Is it possible to pull the model ID of all agents, living or not?

**Comment by DubbleClick** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/4fdaf8ea057b407d702e2f0d2e3799b926342eac

uses gadget id. gadgets do not have a model id.
