### ISSUE TITLE
Damage meter displays in incorrect position after allies are added to party window

### ISSUE THREAD

**Issue by adituv** [gwdevhub/GWToolboxpp#1078]
Title.  If enough allies are added to party window to force it to expand upwards, the damage meter displays where it should have been before expansion.  I assume we currently look at the "target position" of the party window rather than its actual calculated position.

This likely applies to bonds and anything else that draws attached to party window.

**Comment by DubbleClick** [comment]
Ah, I think I fixed this for growth into the right, but didn't clamp the values for the y axis, because I couldn't think of a situation where it would come into play. Guess that's the situation!

**Comment by DubbleClick** [comment]
someone check if this implicitly fixed with the WindowPosition changes
