### ISSUE TITLE
Add salvage option for any drops that can give conset materials

### ISSUE THREAD

**Issue by JimRaynerd** [gwdevhub/GWToolboxpp#1082]
Now that items have salvage results info, is there a chance to turn salvage kits into their ultimate form by adding a new option to only salvage items that give conset materials regardless of item rarity, could be named: "Salvage into conset materials". This way it adds a single extra option and not 4 (one for each rarity).

**Comment by 3vcloud** [comment]
Main points here are that salvage kits are inexpensive, salvaging all items whilst giving a checkbox list as it is at the moment frees up inventory space, and material value of items salvaged is usually more valuable than the item itself.

The only benefit to your approach would be saving salvage uses, and you’ll end up wanting to salvage more than that for the reasons mentioned above
