### ISSUE TITLE
Add functionality to Load/Unload Modules on /tb load presets

### ISSUE THREAD

**Issue by apoguita** [gwdevhub/GWToolboxpp#1083]
right now if you /tb load preset and a module is unloaded it does not get loaded proper.
similar thing happens when you have a module loaded and then /tb load preset and the preset have it unloaded... sometimes work, sometimes not, depends on the module.

delegating config status to loaded module checkbox gives problems as it is with different configs.

**Comment by 3vcloud** [comment]
Thanks for the ticket, but this is difficult to understand. Do you have an example of a module that doesn’t unload properly?

**Comment by apoguita** [comment]
the problem is of more occurrence when loading a preset that uses a module that has been deactivated beforte in the default config

lets say...
you have pcons module deactivated on stamdard layout, trhen /tb load config1, who has it enabled.. well in that case it does not load the module.

"Do you have an example of a module that doesn’t unload properly?" ill have to make tests again, it happened to me when i was configuring my presets, not every module had that problem, let me do some more tests and ill add the info here.
