### ISSUE TITLE
Hotkey to ping current target

### ISSUE THREAD

**Issue by HiImFlo** [gwdevhub/GWToolboxpp#1086]
It would be great to have a hotkey to ping the current target, that does not require holding the "Action: Suppress Action" GW key (shift by default)

The hotkey shouldnt do anything if there is no current target

This might fit well into the "Execute..." hotkey category

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/9ae6d8a582e70145590e4b149db06b800e0b5ce0
