### ISSUE TITLE
Client locks up when trading or trying to view items while in the inventory.

### ISSUE THREAD

**Issue by BearsMan** [gwdevhub/GWToolboxpp#1089]
![Screenshot 2024-05-16 064933](https://github.com/gwdevhub/GWToolboxpp/assets/34116754/9c8f3e1d-a866-479b-8bdf-3b9af9c6edaf)
![Screenshot 2024-05-19 141128](https://github.com/gwdevhub/GWToolboxpp/assets/34116754/b45e3635-28a1-4f24-b208-965576c6c557)
The game completely locks up when using Toolbox, I confirmed this while in a trade and trying to trade an item and when trying to view an item in its inventory, such as the hero's handbook.

**Comment by 3vcloud** [comment]
Can't replicate this, I'll close it until you can retry with just toolbox and no other mods

**Comment by BearsMan** [comment]
Sure, I will have a look when I can.

**Comment by BearsMan** [comment]
https://youtu.be/5QCd_F0FKtc

I added a video here. This is running with Toolbox only and no texmods. If you want to reopen this issue.
