### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Akroma97** [gwdevhub/GWToolboxpp#1102]
Hello

I cannot install GWToolbox...

When trying i get the following Error dump file.

RegGetValueW failed: {status:0x2, KeyName:'asadmin'}
RegGetValueW failed: {status:0x2, KeyName:'noupdate'}
PathSafeCopy: copy C:\Users\Username\Downloads\GWToolbox.exe failed (5, Access denied.)
CopyInstaller failed
Failed to install

How can i fix this ?

**Comment by 3vcloud** [comment]
Looks like copy C:\Users\Username\Downloads\GWToolbox.exe failed with an error of Access denied.

https://discord.com/channels/223619617048756224/1072200067626323988

**Comment by Akroma97** [comment]
hey thanks for help, but your link is to a forum with many post, i tried looking but none of them solves the issue.....

What is the name of the thread you say i should look at ?

Br Jens

**Comment by DubbleClick** [comment]
Looks like copy C:\Users\Username\Downloads\GWToolbox.exe failed **with an error of Access denied**.
