### ISSUE TITLE
Toolbox Mini-map is hidden even though it is checked in settings.

### ISSUE THREAD

**Issue by BearsMan** [gwdevhub/GWToolboxpp#1109]
![gw021](https://github.com/gwdevhub/GWToolboxpp/assets/34116754/bbd30c3b-253b-4c17-8bc2-370beddd9cf8)
After updating to Toolbox version 6.19, I immediately noticed that the TB Mini-map was hidden on launch. I turned the setting off and back on again, and it did not have any effect. This could be patched with 6.20 Hotfix. I wanted to add it here.

**Comment by BearsMan** [comment]
Fixed, closing.

**Comment by 3vcloud** [comment]
How?

**Comment by BearsMan** [comment]
I just re-snapped the GW compass from the TB Mini-map and put it to the compass's original size that I had it on.

All I did was turn on GW Compass via F11 Graphic Options and snap GW Compass via the Mini-map option in TB and it showed back up.

**Comment by 3vcloud** [comment]
Ok so minimap isn’t working without compass showing, which is a bug

**Comment by BearsMan** [comment]
> OK so minimap isn’t working without the compass showing, which is a bug

Oh, okay. Sure thing. Good catch. I thought it was just me.
