### ISSUE TITLE
Can't change chat colors with plugins loaded

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1117]
`SetSenderColor` sets the color for the current gwca instance, the next `GetSenderColor` calls the original function, which the plugin has hooked and replaces with its own `ChatSenderColor[chan]`, which is still the old color

**Comment by 3vcloud** [comment]
This is a problem caused by a third party dll hooking into the same gw functions, not with toolbox. Fix it at the plugin level.

**Comment by DubbleClick** [comment]
The only way to fix it is to unhook GetSenderColor in the plugins, or to send a UI message that lets plugins change their ChatSenderColors when toolbox changes theirs. Agree that it's not a toolbox bug, but a gwca one.
