### ISSUE TITLE
[Feature] Color Zaishen Quest Markers

### ISSUE THREAD

**Issue by franneck94** [gwdevhub/GWToolboxpp#1118]
![image](https://github.com/gwdevhub/GWToolboxpp/assets/20141069/9d3233ab-d2ce-4816-9ad3-fe4b13a4b08b)

My idea is, if the character has already finished  for example the current daily zaishen mission in NM and HM, to color the exklamation mark not in green, but in gray instead.
So i can directly see, i dont have to do this for gwamm.
Yes i know i could look it up in the completion module, but this would be just a cool QOL  feature.

**Comment by 3vcloud** [comment]
Also implement highlighting on the daily quests window - in the proposed state its only relevant when you're in an outpost with the daily quest givers, which would be a bit niche

**Comment by 3vcloud** [comment]
lol why would you park your characters anywhere if you're a casual player - I check character completion and the daily quests window if I want a bit of down time playing the game

**Comment by 3vcloud** [comment]
We can't change the colour of the overhead markers, but we'll shelf this until you've had a play with the changes to the daily quest window

**Comment by franneck94** [comment]
Thanks for adding this.
