### ISSUE TITLE
Widget - Effect Durations: Old Timers Remain

### ISSUE THREAD

**Issue by SpiralEnergy** [gwdevhub/GWToolboxpp#1120]
When a buff is re-applied before the original buff expires; the timer for the original isn't cleared. It remains 'behind' the newer timer and can effect the time that is shown.

Example case: Vow of Silence Dervish, 11 mysticism with a +20% enchant duration scythe
```
Cast Vow of Piety   [24 seconds duration] (refreshes after an enchantment ends)
Cast Grenth's Aura  [24 seconds duration, 10 second cool down]
Cast Vow of Silence [11 seconds duration, 10 second cool down] (expires & refreshes Piety)
```
Recast Grenth's Aura and VoS off cooldown

Sometimes Piety's or Grenth's timer will go up to 29 seconds, then after 3 seconds-ish, corrects itself. Sometimes the older timer will stay at the forefront until it expires. Sometimes the older timer will come to the forefront for a short bit before the newer timer comes back to the forefront.

A little slower to test:
Intimidating Aura - 60 seconds duration, cooldown 20 seconds
Sometimes the newer timer doesn't come to the forefront when recast.

**Comment by DubbleClick** [comment]
was already fixed
