### ISSUE TITLE
Quest marker not appearing in the minimap

### ISSUE THREAD

**Issue by raben1** [gwdevhub/GWToolboxpp#1132]
They appear invisible in the minimap, adjusting the
Quest Marker color/transparency at Symbols doesn't
change at all.

![quest markers](https://github.com/gwdevhub/GWToolboxpp/assets/123206408/c5347e22-ebc0-4ef2-b74d-a937cedc0fd8)

**Comment by DubbleClick** [comment]
wtf is that screenshot

**Comment by BearsMan** [comment]
I second that, it is a bad screenshot.

**Comment by raben1** [comment]
Can't figure other way to show something invisible in the minimap, I just did a huge zoom in to show the light purple quest markers there, GtoB Zaishen quest givers in the example, but same for other quest markers like Rasti in fow :(

**Comment by DubbleClick** [comment]
So the semi-transparent purple are the quest markers. Will figure out what's wrong, thank you.

**Comment by DubbleClick** [comment]
FYI, you can set the minimap to render as a circle (and it's the default), so it doesn't have to be ugly with a rectangle around.

**Comment by raben1** [comment]
I just like that square ugly minimap over the circle compass haha

**Comment by 3vcloud** [comment]
It was set to a stupid transparent purple colour by default a few versions ago. I set it back, but any saving you've done would have set it that colour now.

![image](https://github.com/gwdevhub/GWToolboxpp/assets/10796356/feed289f-257a-44b6-8e9d-60776ed15453)
