### ISSUE TITLE
Failed to create outgoing log file - GWToolbox++

### ISSUE THREAD

**Issue by andywontdie** [gwdevhub/GWToolboxpp#1136]
Just updated to version 6.22 and it is giving me the error above.  All permission check out, AVG rules are all in check, I run as administrator, everything I can think of. The log shows empty, and the only thing that pops up in the Event log is this:

windows.gaming.gamebar.presenceserver.internal.presencewriter did not register with dcom within the required timeout.

Any help will be greatly appreciated!

Thanks!

**Comment by DubbleClick** [comment]
- Go to your GWToolbox folder by navigating to `%USERPROFILE%\Documents\GWToolboxpp` in a File Explorer window. Is there a GWToolboxdll.dll? A folder named after your Computer name?
 - If there is no GWToolboxdll.dll, download the latest dll from https://github.com/HasKha/GWToolboxpp/releases, and put it in the GWToolbox folder, retry launching.
- If you are getting a font can't be loaded error, download https://github.com/HasKha/GWToolboxpp/blob/master/resources/Font.ttf and put it in the GWToolboxpp/Computername folder.


We need more information to really suggest anything here. Did you download the latest launcher from the website (a few days old)? What *exactly* happens when you launch toolbox. Does the window pop up? Can you select a character name? Etc. etc. etc.. Describe it as accurately as anyhow possible, because remember, we cannot see your pc.

**Comment by andywontdie** [comment]
DubbleClick,

I downloaded the newest from the main site and when I run as admin, the box will come up and I will select the account and click ok and then I get the error, but no entry in the toolbox log. I didn't have dll file at first, but I just downloaded and tried again and same result. I have attached a screenshot of how my gwtoolbox is setup and has worked in the past. Please let me know if you need any more details or settings. 
![Screenshot 2024-06-30 013403](https://github.com/gwdevhub/GWToolboxpp/assets/174227688/9ac21df2-7be4-4762-a3cd-c39c2cad7288)

**Comment by DubbleClick** [comment]
Please read my message again. Downloading it into a random folder doesn't do anything.

**Comment by andywontdie** [comment]
I found that folder, and when I run that version of it, it tells that the app doesn't appear to be installed and asks if I want to install it, when I say yes, nothing happens and this behavior repeats upon successive attempts. But I haven't used this folder in ages. This app has worked from my current folder for last year, with updating every time I was prompted so I don't know what is different about this this time.

**Comment by DubbleClick** [comment]
The "app" is the dll in the toolbox folder. The file you are executing from another folder is simply a downloader & launcher. Either way, I *once again* ask you to read my message. You still haven't answered the very first question of it.

**Comment by andywontdie** [comment]
> * Go to your GWToolbox folder by navigating to `%USERPROFILE%\Documents\GWToolboxpp` in a File Explorer window. Is there a GWToolboxdll.dll? A folder named after your Computer name?
> * If there is no GWToolboxdll.dll, download the latest dll from https://github.com/HasKha/GWToolboxpp/releases, and put it in the GWToolbox folder, retry launching.
> * If you are getting a font can't be loaded error, download https://github.com/HasKha/GWToolboxpp/blob/master/resources/Font.ttf and put it in the GWToolboxpp/Computername folder.
> 
> We need more information to really suggest anything here. Did you download the latest launcher from the website (a few days old)? What _exactly_ happens when you launch toolbox. Does the window pop up? Can you select a character name? Etc. etc. etc.. Describe it as accurately as anyhow possible, because remember, we cannot see your pc.

First bullet - Yes, that dll file was there and yes, the folder was there too. 

Second bullet - Did that any, downloaded the newest one and placed it both locations. Same result. 

Third bullet - Not having this issue. 

First question in second paragraph - Yes, downloaded version 6.22 from the GWToolbox++ site from the button at the top of the page

Second question - Run it, windows admin prompt pops up, say yes, window with character select comes up, select character and click ok. Error with message stated in the title of this thread comes up. Check log, no entries, which unusual as there is typically something to guide me. 
When I attempt this from the default folder you mention, with the updated version of the launcher and the dll, the game will crash and AVG will see it as a threat. Once I un-screw that mess and try again, it gives me the same "Failed to create..." error as before. 

Please let me know if there is any further info needed.

**Comment by DubbleClick** [comment]
That's enough info to give a good hint: this definitely sounds like AVGs doing. Sounds like it allows the exe to run, but doesn't like injecting the dll. Try excluding the gwtoolboxpp folder (zero reason to keep a separate exe outside that folder, by the way, just create a shortcut instead) from AVG entirely. If even that doesn't work, disable AVG entirely to see if that fixes the issue.
