### ISSUE TITLE
What date nicholas wants a trophy

### ISSUE THREAD

**Issue by franneck94** [gwdevhub/GWToolboxpp#1148]
It might be more useful tooltip to say what date nicholas wants a trophy, instead of how many he wants.

So instead of:
"Nicholas wants {X} of these!"
It could be:
"Nicholas wants these next on {Date}!"
or
"Nicholas wants these in {X} weeks!"
or
"Nicholas wants {X} of these in {Y} weeks!"

**Comment by RiftLurker** [comment]
Since we discussed this on discord and I don't feel like setting up an environment right now below some pseudocode to find the next timestamp by index.
```
fullCycleDuration = count * interval
cycles = floor((now() - start) / fullCycleDuration)
next = start + cycles * fullCycleDuration + index * interval

if (next < now)
    next += fullCycleDuration    
```
