### ISSUE TITLE
/zq prints out all Zaishen quests

### ISSUE THREAD

**Issue by Chromos-Def** [gwdevhub/GWToolboxpp#1151]
Pointed out the features of /zb /zm etc. to some people in a dungeon and one of them suggested /zq to print out all of them in fell swoop.

Small but sounded like a good idea so I'm submitting.

**Comment by franneck94** [comment]
so
/zq 5
to print the next 5?

**Comment by Chromos-Def** [comment]
Negative.

I mean current days Zaishen quests

Typing /zq would print out

/zb
/zc
/zm
/zv

In one single fell swoop, so just 4 lines of text.

**Comment by franneck94** [comment]
Ah okay, y that sounds cool

**Comment by Chromos-Def** [comment]
> /today

Oh my, didn't know this one existed. Yeah that covers it :P
