### ISSUE TITLE
Chat history poofs when TB gets auto disabled such as inside guild hall

### ISSUE THREAD

**Issue by Chromos-Def** [gwdevhub/GWToolboxpp#1152]
Any chat that occurs while inside of my guild hall gets wiped from existence whenever I zone out back into an area where toolbox re-enables.

![gwchathistory](https://github.com/gwdevhub/GWToolboxpp/assets/47635128/4ab1de42-d268-4ef2-a444-bc7c9cbdf8ad)

4min gap in screenshot, even though my alliance was being some chatty Kathy's and I was discussing further with the person I was trading.

**Comment by 3vcloud** [comment]
Disable chat log module until it’s fixed
