### ISSUE TITLE
Incorrect encoding in `Active Quest Info` window

### ISSUE THREAD

**Issue by truekenny** [gwdevhub/GWToolboxpp#1157]
![изображение](https://github.com/gwdevhub/GWToolboxpp/assets/3448197/508fff62-7d70-4cb4-92d7-66bfaebcb4c6)

Switched from version `6.16` to `6.22`.
In the new version I found `Active Quest Info`.

Previously I added the font `Font_Cyrillic.ttf` for the `Completion` window.

On the screenshot:
1. `Active Quest Info` window - encoding is incorrect
2. `Quest log` - game window with an example of what the text looks like
3. `Completion` window - the encoding is correct

**Comment by DubbleClick** [comment]
@adituv maybe confirm this fixes it, idk how to set up other languages

**Comment by 3vcloud** [comment]
Bad, don’t rely on %S in a printf

**Comment by DubbleClick** [comment]
https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170&viewFallbackFrom=vs-2019

it's a microsoft extension :/

**Comment by adituv** [comment]
It doesn't work anyway.  I'm working on it.

**Comment by adituv** [comment]
I thought it might have been an encoding issue, but it seems it is

**Comment by 3vcloud** [comment]
Yeh if it’s question marks it’s just the font that’s dodgy - put the fonts from the resources folder into your toolbox folder and run it
