### ISSUE TITLE
Add Request: auto salvage

### ISSUE THREAD

**Issue by Lemaggo** [gwdevhub/GWToolboxpp#1161]
Would it be possible when I click on a stack to select, Salvage all or something like that?

Thanks in advance and also for your use of this wonderful plugin.

Lemaggo

**Comment by 3vcloud** [comment]
No, the code debt to traverse across suitable salvage kits and the related logic isn't worth it when we've got a context menu on each kit, and the further automation can't be justified when we have the functionality working well in its current state. Buy a superior salvage kit and use that.

Requesting ability to burn through a whole stack of a specific salvageable item without dependency or interaction with a kit is also pretty bot-like behaviour and could be easily abused.
