### ISSUE TITLE
Suggestion Toggle for hotkeys /useskill

### ISSUE THREAD

**Issue by Bloxor21** [gwdevhub/GWToolboxpp#1162]
So basically what I’m trying to do is making the corresponding key (let’s say skill 2) for a skill (let’s say SF) being toggleable.

The way it is right now, you can make a hotkey for enabling /useskill and one for disabling.

Basically this functionality, but on one key, that if you press it, it would toggle on the /useskill, and if you press it again, it would disable it.

This is really helpful, if you’re gonna wanna recast a certain skill, but don’t want it recast 100% of the time, so once you’re done with like forge in FoW for example, you can disable it until you need it recast Shadowform on cooldown again.

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/1bb797328107a77e03b71ada4acbd9d3172c0b52
