### ISSUE TITLE
Crash when activating pcons on loading screen.

### ISSUE THREAD

**Issue by raben1** [gwdevhub/GWToolboxpp#1167]
When zoning from an explorable area to an outpost.
Auto-disable pcons on map change ON.
Clicking "Enable" during the lapse where there is no counter on pcons produces the crash.
![pcons](https://github.com/user-attachments/assets/6f3cf117-e824-4639-b43e-cfb40abaca3c)

**Comment by 3vcloud** [comment]
Sending a crash dump to me on discord would help debug this - should be one in the crashes folder of gwtoolbox

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/b830b99e07a335d374d6b761ea012488fde34286
