### ISSUE TITLE
Opening storage from TB assumes account has anniversary tab

### ISSUE THREAD

**Issue by Chromos-Def** [gwdevhub/GWToolboxpp#1173]
Using the hotkey or clicking the open xunlai chest from the info window assumes the account has anniversary storage, when in fact my recently purchased account does not have it.

It did not allow me to deposit any items.

Walking up to the xunlai chest in the outpost and interacting with it there shows properly that I do not own the anniversary storage.

**Comment by DubbleClick** [comment]
Just to confirm, the bug is that you cannot deposit (and withdraw?) any items? With ctrl + click? Always?

**Comment by Chromos-Def** [comment]
To confirm, nothing to do about ctrl + click.

It is when you use

Open xunlai chest button from the Info panel
or
If you setup a hotkey to show the xunlai storage through TB hotkeys

**Comment by DubbleClick** [comment]
Oh you mean it's a VISUAL bug where the panel shows you the anniversary storage is unlocked, but it isn't.

**Comment by 3vcloud** [comment]
Info on whether anniversary pane and materials pane is sent from the server, and passed into the second argument of the ui message to open the chest. We'd need to listen for this and save whether the account has is unlocked or not, to disk against email address.

**Comment by DubbleClick** [comment]
Wonder if the client doesn't cache this somewhere. Not sure I'm the biggest fan of caching this simple flag to a file.

**Comment by 3vcloud** [comment]
Not cached, and not needed to be by the client; these things are only accessed by the game when its told to open the storage window, and this is explicitly done via StoC packet that contains these flags. Its held in memory for the life cycle of the storage window, then cleared on frame close or map change
