### ISSUE TITLE
Replace default title for Asuran missions

### ISSUE THREAD

**Issue by Crocross** [gwdevhub/GWToolboxpp#1174]
Most missions in EotN have the proper title set when using `/title` however the following two Asuran missions use the default title:
- The Elusive Golemancer
- Finding the Bloodstone

It would be nice if it activated the Asuran title by default.

The third Asuran mission (G.O.L.E.M.) uses delver by default but considering all the enemies are destroyers I don't think this is an issue, just thought I'd note it. This is also the same case with A Gate Too Far for Norn.

**Comment by 3vcloud** [comment]
Neither of these areas benefit from the asura title. The explorables leading to them should have it set correctly though

**Comment by Crocross** [comment]
You do get the energy benefit in the areas
