### ISSUE TITLE
Toolbox circumvents storage unlock fee

### ISSUE THREAD

**Issue by shoeffner** [gwdevhub/GWToolboxpp#1176]
While playing on a character for whom I didn't pay the storage unlock fee of 50g, I accidentally opened up the chest and was able to withdraw/deposit stuff.
I don't think this should happen, even though it's only 50g.

**Comment by 3vcloud** [comment]
Theres no way to determine the state of this until the player talks to a chest or a xunlai agent. We'd have to record this info against each character and load it up to check when tb starts, which isn't worth the hassle for a 50g storage fee that is quickly progressed
