### ISSUE TITLE
Toolbox doesnt work in Guildhalls?

### ISSUE THREAD

**Issue by Lemaggo** [gwdevhub/GWToolboxpp#1177]
Hey DubbleClick, 
do you know why I can't use Toolbox in the guild hall? 
Whenever I travel there, the entire UI disappears and the hotkeys don't work, but are there working again when I travel somewhere else. 
This only happens to me in the guild hall.

**Comment by 3vcloud** [comment]
Toolbox isn’t allowed in pvp areas

**Comment by MangelMaxime** [comment]
@AlexMacocian Thank you I will give it a try
