### ISSUE TITLE
Fetch salvage info from GuildWars process

### ISSUE THREAD

**Issue by AlexMacocian** [gwdevhub/GWToolboxpp#1203]
- Scan for assertion formula < ITEM_FORMULAS
- Look for the table address in that function

That table has (I think) 1497x 20-byte entries.  h0010 is the number of entries in the material table, and h0014 is the pointer to the material table

![image](https://github.com/user-attachments/assets/dbc0c90c-b043-499a-8738-eec27e6c9f9b)

![image](https://github.com/user-attachments/assets/2b27e0f9-7519-4026-8453-487d95080ef2)

Eg. formula info
![image](https://github.com/user-attachments/assets/aca57a17-0b87-4aa8-8a77-4b3e562f6bfe)

**Comment by 3vcloud** [comment]
We’re doing this

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/b058952f176bb4bc7fae4565827a78973fa2062b
