### ISSUE TITLE
Option for users to broadcast party search

### ISSUE THREAD

**Issue by AlexMacocian** [gwdevhub/GWToolboxpp#1210]
Users could enable an option to broadcast their party search to party.toolbox.com, similarly to the bots

**Comment by 3vcloud** [comment]
This is not a good idea, its like kamadan chat allowing people to send bullshit trade messages

**Comment by AlexMacocian** [comment]
Yeah it'd suffer from the same issues as kamadan (and require similar fixes), but a lot of people would find it really useful

**Comment by AlexMacocian** [comment]
Or let's see if there will be people asking for this
