### ISSUE TITLE
Travel menu: 't' keyboard shortcut jumps to 'The Amnoon Oasis'

### ISSUE THREAD

**Issue by nomadicTree** [gwdevhub/GWToolboxpp#1211]
When pressing 't' to jump to locations whose names begin with 't', it jumps to 'The Amnoon Oasis' which is grouped with the 'a' locations. Please change it so that 'The Amnoon Oasis' is skipped and instead, pressing 't' jumps to the locations whose name begins with 't'.

**Comment by 3vcloud** [comment]
This is part of the imgui ui, and isn't really worth the rewrite. Use the `/travel` command to easily travel to locations instead, using partial name search e.g. `/tp amn` would take you to The Amnoon Oasis as an example
