### ISSUE TITLE
GameworldRenderer: always render first quest path line from current player position

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1216]
Need a way to find the actual player feet position without calling QueryAltitude. The current version of it updating every 100 gwinches makes me dizzy while playing. It should smoothly update every frame.
![image](https://github.com/user-attachments/assets/f8fcaa60-b021-471c-93aa-a103211af4da)

critical because it hurts my brain, but I need it to figure out where the fuck to go

**Comment by 544449** [comment]
Player feet z pos is actually name_tag_z of the Agent struct.
