### ISSUE TITLE
fix zplane calculated height

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1219]
easy to test in factions kaineng area, most bridges calculate zppos under the bridge

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/blob/29f4c1e1d1da29ef9edd9d5144b16f82d43ec174/GWToolboxdll/Widgets/Minimap/GameWorldRenderer.cpp#L107

**Comment by DubbleClick** [comment]
that part isn't actually the problem, the problem is the interpolation code between two points not getting the correct zplane I think

![image](https://github.com/user-attachments/assets/6a5c7230-eb67-4b8b-a064-6e99bfdc5ad0)

A and B are on zplane 0 because there's no ground below, The points in the bridge inherit zplane 0 from points A and B, but the bridge itself is on zplane 1 as there's ground below it.

**Comment by 3vcloud** [comment]
There’s no inheriting, it just guesses - this code is the issue. Change this and you’ll fix it
