### ISSUE TITLE
[Beta] Crashes in explorable area (Lethenda Bog)

### ISSUE THREAD

**Issue by FelixGrafschmidt** [gwdevhub/GWToolboxpp#1230]
I experienced two crashes in relatively quick succession after playing without issues for about 30 minutes.

Here are the crash dumps:
[6.23beta1-20240910-191253-52764-13220.dmp](https://github.com/user-attachments/files/16948522/6.23beta1-20240910-191253-52764-13220.dmp)
[6.23beta1-20240910-191959-29312-48176.dmp](https://github.com/user-attachments/files/16948523/6.23beta1-20240910-191959-29312-48176.dmp)

Thank you very much for your support!

**Comment by 3vcloud** [comment]
What were you doing in the first crash? Looks like something to do with armor slots, so may be related to using the armory module

**Comment by FelixGrafschmidt** [comment]
I don't remember exactly, I was in the area for vanquishing and exploration. I think I was salvaging something just before the second crash (manually, not via the toolbox right-click menu), but I do not remember what exactly I was doing before the first crash. I have never really used the armory module, but I know that I looked through some modules that day, since this was the first session with the Beta update.

**Comment by 3vcloud** [comment]
ok thanks. The second crash has been found and will be fixed
