### ISSUE TITLE
Integrate dsoal into gw via toolbox module

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#1231]
https://youtu.be/qQUU-79bm6c?t=521

https://guildwarslegacy.com/forum/thread/10525-announcing-dsoal-gw1-3d-positional-audio-and-eax-effects-for-everyone/

Lots of hoops to jump through but makes a massive difference to casual players. I've been playing with it for years, but we can integrate the whole process and wrap it up into a module

**Comment by Irisier** [comment]
not that SCW is already in the process of making DSOAL unnecessary, see this comment 3 months ago from him on reddit: https://www.reddit.com/r/GuildWars/comments/1chu6ac/comment/laubmgr/

**Comment by 3vcloud** [comment]
Yep, looks like it'll be done on anet side after having a chat today; I'll block this until we know more

**Comment by 3vcloud** [comment]
Fixed in gw build 37461
