### ISSUE TITLE
[6.24] Example plugin crashes in initialize

### ISSUE THREAD

**Issue by JaborGW** [gwdevhub/GWToolboxpp#1260]
**To reproduce:**
* Inject TB 6.24 into GW (Tested using an up-to-date GWLauncher with [this ](https://github.com/gwdevhub/GWToolboxpp/releases/tag/6.24_Release)DLL)
* Load the example plugin

**Issue:**
* GW crashes

This seems to affect all plugins calling `GW::Initialize`, in particular every `ToolboxUIPlugin`. Commenting out the ChatMgr initialize "fixes" the crash.
Compiling in debug mode, the first assert that fails is https://github.com/gwdevhub/GWCA/blob/1c537e60350b316dccc0b78bba7c8a01d25d956d/Source/ChatMgr.cpp#L355

**Comment by JaborGW** [comment]
@3vcloud This was tagged as "Won't implement". Does that mean you could not reproduce an issue, or that plugin support is dropped?

**Comment by DubbleClick** [comment]
Plugin support isn't dropped, it never really existed. I'm doing my best to make sure it works when I find time, but there was never official support.

For a short amount of time, until the compiler update, it makes no sense putting work into it. Expect it to work in 6.26 again or feel free to create a gwca PR that makes it work for multiple initialisations before that.

**Comment by JaborGW** [comment]
> Expect it to work in 6.26 again or feel free to create a gwca PR that makes it work for multiple initialisations before that.

Ah, so the "Won't implement" is specific to the 6.24 from the request; I took it to mean it will not be looked at for any future version.
Thanks for the clarification!

**Comment by 3vcloud** [comment]
GWCA won't work when injected more than once, which will probably cause issues with plugins too
