### ISSUE TITLE
New "are you sure?" prompt pops up even if character hasn't completed the mission

### ISSUE THREAD

**Issue by aappani** [gwdevhub/GWToolboxpp#1265]
A prophecies character receives the prompt "are you sure?" on new missions. After clicking "no" you can start the mission without prompt. Re-entering the mission outpost will prompt again. I am not sure if characters from other campaigns receives the prompt.

In my case I have level 20 Character with LDoA and while doing NM campaign I receive the prompt in all missions so far.
![14_11_2024_201758](https://github.com/user-attachments/assets/fe21e337-6bc3-48b8-a165-bdb171de97e8)

**Comment by DubbleClick** [comment]
Quick question, do you have the CompletionWindow disabled in Toolbox Settings?
![image](https://github.com/user-attachments/assets/f0494d47-926b-4be4-8104-eebb4b141627)

**Comment by aappani** [comment]
I'm not sure what CompletionWindow  is in toolbox. Today I was playing another ldoa character and I was not able to reproduce the bug. This might be one time bug, I'll see if it comes again.

Here's my settings:
![kuva](https://github.com/user-attachments/assets/569940be-382d-48f2-a913-5aad419f34ad)
