### ISSUE TITLE
LoginModule Auto login not working

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#1266]

**Comment by DubbleClick** [comment]
the logic still works, when I attach a debugger, but without attaching one it doesn't.

will investigate later

**Comment by DubbleClick** [comment]
putting gw into suspended state for a short bit while toolbox initialises fixes it. maybe this wasn't a direct update from gw, but from a change you did in gw launcher? @3vcloud

**Comment by 3vcloud** [comment]
Gwlauncher is supposed to put the game into a suspended state to inject dlls so idk what you mean - I’ve got a bit of time today to look at it

**Comment by 3vcloud** [comment]
So it turns out this is literally just because the game boots faster than tb now - by the time the login module is ready, its already loaded. This will need revisiting

**Comment by DubbleClick** [comment]
We could slap a plaster on it from the gw launcher side and suspend gw initialisation for an extra second or so

**Comment by 3vcloud** [comment]
yeh been pissing around for a few hours, see if you can just add a delay in gwlauncher

**Comment by AlexMacocian** [comment]
The delay will fix it. I've encountered this issue some months ago and added a short delay in Daybreak before resuming the GW thread. 
Since then I've never had problems with toolbox not initializing in time.

**Comment by 3vcloud** [comment]
No need for the delay, moved the init process to not be on a separate thread inside toolbox
