### ISSUE TITLE
[Kamadan] trade chat is not working properly

### ISSUE THREAD

**Issue by sendaimono** [gwdevhub/GWToolboxpp#1271]
There is degraded performance of webpage. Only first ~50 items are listed + search option is not working at all. 

I don't see any extra repo for Kamadan, so this is why I post it here

**Comment by jhun266** [comment]
Both Kamadan and Ascalon trade chats appear to have stopped working/updating 6 days ago.

**Comment by jhun266** [comment]
Many thanks for fixing this.

**Comment by sendaimono** [comment]
Hey. So the issue still persists. Now it's down since 2 days. Previously it was flickering (sometimes online, sometimes offline)

**Comment by sendaimono** [comment]
Hey @3vcloud. 
Thanks for fixing it previously, but the issue still persists. Now it's down since 2 days. Previously it was flickering (sometimes online, sometimes offline)

**Comment by 3vcloud** [comment]
https://discord.com/channels/223619617048756224/679408286084235274/1311235302622367774
