### ISSUE TITLE
Bottom Window Title bar feature request

### ISSUE THREAD

**Issue by Doxorn** [gwdevhub/GWToolboxpp#1272]
An option for each window module to expand upwards instead of downwards. Would make possible to keep some windows at the bottom of the screen collapsed until it is needed.
As seen in the pictures below, if I want a window on the bottom of the screen I can't collapse it without making it look weird.
![window_expanded](https://github.com/user-attachments/assets/1bb6f431-511e-4146-8c5a-e1d9b5d889a4)
![window_collapsed](https://github.com/user-attachments/assets/64f4767f-6731-4641-977e-1ae719cc5abf)

Here is an example how I imagined it with my paint skillz:
![this_would_be_awesome](https://github.com/user-attachments/assets/dce959e4-858b-4478-85a4-afd14e6d8681)

**Comment by DubbleClick** [comment]
There is an option that keeps windows inside screen bounds. It can do what you want there.
