### ISSUE TITLE
Pathfinding keeps displaying with window setting disabled

### ISSUE THREAD

**Issue by raben1** [gwdevhub/GWToolboxpp#1275]
Here shows up when the quest is completed and pending reward.
![pathf completed - Copy](https://github.com/user-attachments/assets/610d4d31-6fb8-459f-ad7d-d5bd9e90ce1f)
When an objective is completed, not before.
![pathf mission - Copy](https://github.com/user-attachments/assets/1e9d2bb9-a5e3-4727-9ff4-0c9eef0c308b)
Only in outpost, when getting outside it disappears.
![pathf zb - Copy](https://github.com/user-attachments/assets/2fa3fa4e-3102-45f2-afb6-14bc26955efe)

**Comment by 3vcloud** [comment]
![image](https://github.com/user-attachments/assets/8efbbe13-a820-4018-a2c4-ae5b27379cc6)

**Comment by raben1** [comment]
Is that new addition? I can't see it there
![quests path](https://github.com/user-attachments/assets/9edd1eb9-4f07-43cf-a053-69655f39b7ae)

**Comment by DubbleClick** [comment]
New setting. But the first two checkboxes are what you're looking at, anyway.
