### ISSUE TITLE
TB /cam fog off feature no longer works.

### ISSUE THREAD

**Issue by BearsMan** [gwdevhub/GWToolboxpp#1277]
After updating to v6.25, I have tried using /cam fog off to eliminate the fog in-game. As soon as I hit enter, the command doesn't work. Could be a bug? 
![gw024](https://github.com/user-attachments/assets/d008a366-eacb-4ff5-86e3-3de4685dec5c)

**Comment by BearsMan** [comment]
It is still not working for me. I have tried in several areas. I don't even know why it won't turn off even if I hotkey it.

**Comment by 3vcloud** [comment]
Enter gloom and show a screenshot

**Comment by BearsMan** [comment]
> Enter gloom and show a screenshot

Sure thing. Of course.

**Comment by BearsMan** [comment]
![gw005](https://github.com/user-attachments/assets/78c25199-1768-4054-8c35-abc012774c84)
I entered Gloom and used Hotkey /cam fog off and /camera fog off to turn off the fog, which had no effect.

**Comment by BearsMan** [comment]
> Enter gloom and show a screenshot

Okay,  as it turns out. I got this message on Discord. It reads the following: ⁠GWCA / TB++⁠ 
Cam fog off and cam fog on works. They work, but only the other way around. Cam fog off” turns the fog on and cam fog on turns the fog off.

@3vcloud
