### ISSUE TITLE
Blocking messages via chat filter `ShouldIgnore` doesn't flush the message buffer

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#1280]
Tried with `ClearMessageBuffer` but I think theres still an issue

**Comment by DubbleClick** [comment]
I think I had someone open this issue already

**Comment by DubbleClick** [comment]
hmm, can't find it anymore, so I guess we'll keep this open

**Comment by halogod35** [comment]
This one? #1273
