### ISSUE TITLE
Minimap issues: Can't see each others drawing and drawing on the in game compass crashes game if toolbox is running

### ISSUE THREAD

**Issue by haxgw** [gwdevhub/GWToolboxpp#1284]
Could reproduce this several times regardless of if I had the toolbox minimap up. Others in game reported similar issues. At one point I could not draw on the Toolbox minimap either but I could not reproduce that.

**Comment by mdbauman** [comment]
Just commenting to add a dump. Drawing on Toolbox minimap works fine, but drawing or pinging on default minimap causes a crash immediately.
[6.25-20241125-153713-6744-18752.dmp](https://github.com/user-attachments/files/17924065/6.25-20241125-153713-6744-18752.dmp)

**Comment by tkdj6** [comment]
Unable to load a dump, but same issue happening to me and then subsequent boots of Toolbox immediately crash client with no error message.
