### ISSUE TITLE
Chat Filter improvements

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [gwdevhub/GWToolboxpp#179]
Incorrigible Alehound announcement is still missing?? I thought we'd got the code for that one...

Maybe classify lockpicks as rare items? They're worth more money than general unids, and anyone who cares about Wisdom is probably also opening chests.

**Comment by Hour-of-the-Owl** [comment]
Life of the Party

**Comment by Hour-of-the-Owl** [comment]
_____ drops a Destructive was Glaive.

other item spells too I guess

**Comment by Hour-of-the-Owl** [comment]
The mission could not be entered. Please try again later.

**Comment by Hour-of-the-Owl** [comment]
Could it be possible to have certain messages appear in a different colour? For example, when I get an ecto drop, I'd love for "Glob of Ectoplasm" (or the entire message) to be more visible, so I actually notice the message.

**Comment by Hour-of-the-Owl** [comment]
> Maybe classify lockpicks as rare items? They're worth more money than general unids, and anyone who cares about Wisdom is probably also opening chests.

2 and a half years later, can I tempt anyone to care about this?

**Comment by Hour-of-the-Owl** [comment]
____ has started a fireworks display.

**Comment by Hour-of-the-Owl** [comment]
Legendary Survivor... do we have a list of titles we need to find the packet for?

**Comment by 3vcloud** [comment]
Any titles that I havent got here https://github.com/3vcloud/guildwars-chat-app/blob/7b072766f2627cce8cfc782658583be7de3c5618/src/js/GuildWars_StringDecoder.js#L116 but theres no easy way for you to find the code yourself for these
