### ISSUE TITLE
Autocorrect for friend list aliases

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#508]
Wouldn't it be neat if you just typed "Mist" and the chat would suggest our dear friend Misty as who to whisper? This works for in-game character names, but unfortunately not for the friend list aliases that were added later on.

Honestly this is more like a feature that a-net should implement, but I wouldn't hold my breath there...

**Comment by 3vcloud** [comment]
Took a look at the code for this, not worth the extra signature scan(s) and logic
