### ISSUE TITLE
Custom chat commands

### ISSUE THREAD

**Issue by ghost** [gwdevhub/GWToolboxpp#523]
An option to redirect chat commands will be great.

Lets say I travel a lot to vlox and I am lazy AF. So instead of writing "/to vlox" every time, I want to be able to add to myself a shorter chat command "/vlox".

Maybe even an option to trigger a hotkey using chat command.

Is it possible?

**Comment by PostCrafter** [comment]
What's the use case for triggering hotkeys using chat commands?

**Comment by BearsMan** [comment]
> What's the use case for triggering hotkeys using chat commands?

when triggering it it will show up in all chat every time u zone into that map I used it for recruits messaging and I feel its a bad idea to trigger it even time u zone into an area

**Comment by Hour-of-the-Owl** [comment]
We have a finite number of keys available to assign to hotkeys. Being able to trigger them by other means would be useful.

**Comment by NG-Guildwars** [comment]
Will also be useful if we could make a chain of hotkeys

for example: I want that my "\vlox" will do 2 things: trigger "/to vlox" and trigger "/dance"

(just a dumb example but can find something more usfull like chain of dialogs etc")
