### ISSUE TITLE
tips widget

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [gwdevhub/GWToolboxpp#525]
The beginner hints in GW are... somewhat useful... what if TB could add to that? It should be simple enough to implement: just have a text box appear on screen when certain events are triggered. Here are my ideas so far:

- [x] first time buying a Xunlai storage account (you can detect that dialogue being sent, right? and when that's happened once, change the TB settings so the tip won't appear again):
> Type `/chest` into chat to open your Xunlai Chest from anywhere in an outpost, so you won't have to run to the chest every time.

- [x] first time unlocking Koss:
> Heroes in your party gain experience from quests, so remember to add your low level heroes when accepting quest rewards.

- [x] first time using the PvP equipment panel:
> PvP Strength shields give 9 armor when you don't meet the requirement, so unless you can meet the req on a different attribute, use a Strength shield.

- [x] arriving in Embark without having unlocked LA, KC, or Kamadan:
> To get back from Embark Beach to where you came from, talk to the `your homeland` Travel NPC or use the `/tb travel` feature.

- [x] first time arriving in Droknar's Forge (explorable), Divine Path, Throne of Secrets, or Epilogue:
> Talk to `relevant NPC` to receive a `relevant trophy`. Those are worth a lot of money if you sell to another player, so rather than trading it in for a weapon, search on <https://kamadan.gwtoolbox.com> for a buyer.

- [x] a lot of stuff could be for specific missions/quests
accepting Adventure with an Ally:
> If you don't have a friend available to join you for this quest, try adding everyone in Ascalon City (America English district) to your party. Someone will surely be happy to help you.

- [ ] triggering the first cutscene in Nolani Academy:
> Turn right and head south to kill Bonfaaz Burntfur. It's a quicker route to the end - Prince Rurik will be fine on his own.

- [ ] reaching Rornak Stonesledge in Borlis Pass:
> You need to drop a keg INSIDE the snowdrift to the south.

- [ ] accepting Horde of Darkness (can we add in a wiki link for this one? <https://wiki.guildwars.com/wiki/Horde_of_Darkness#Skip>):
> This quest can be slow and annoying. There's a trick to skip most of it, explained on the wiki.

- [ ] can have some useful reminders that are also good for more experienced players too
when creating a new character:
> Type `/bonus` into chat to receive some useful items. You can do this as many times as you like, so long as you're in an outpost.

- [ ] when completing The Time is Nigh:
> Talk to Captain Ahkenchu in Sunspear Great Hall to get Night Falls.

- [x] after speaking to Gwen in HoM:
> Talk to Gedrel of Ascalon in Eye of the North to get a Hero's Handbook and Master Dungeon Guide.

- [ ] when reaching rank 1 in Lightbringer or one of the EotN titles:
> Don't forget to talk to `relevant NPC` in `relevant outpost` to get the `relevant title effect` effect.

- [x] completing Wrathful Spirits with Charm Animal in your bar (and heroes in your party, if we can easily detect that?):
> If you're planning to charm a Black Widow, remember to flag your heroes away so they don't kill it.

- [x] entering a PvE area with Charm Animal on your bar when you already have a pet:
> Charm Animal is only needed for charming a pet. Consider bringing Comfort Animal instead.

**Comment by jongarbott** [comment]
Should this be in the "global" channel i.e. green text, or a GWToolbox++ message in emotes?

**Comment by 3vcloud** [comment]
Should this be in the "global" channel i.e. green text, or a GWToolbox++ message in emotes?

**Comment by Hour-of-the-Owl** [comment]
I think it should pop up exactly like the GW Hints feature.

**Comment by 3vcloud** [comment]
Started looking at this, just tweaked it into a task list format for me to come back to - feel free to add more examples, but obviously not too niche - dont want to have to jump through loads of in-game hoops just to test it

**Comment by 3vcloud** [comment]
Too much code debt to be a benefit atm
