### ISSUE TITLE
Hiding player name(s) in-game

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#590]
So we've recently has a spate of griefers reporting Toolbox users on stream, so there is a use case for being able to hide or obfuscate player names in-game to remove that possibility. Please add comments/suggestions here and I'll add them.

- [x] Inventory Window
- [x] In-game character name tag
- [x] Customized weapons
- [x] ~~Friend list~~ Not relevent to the module (current player name isn't seen)
- [x] ~~Current district~~ Would interfere with other modules if we deliberately overwrite, and too much effort to hook the UI that displays this. An option would just be to hide the district picker via GW options.
- [x] Mercenary heroes
- [x] ~~Guild window (current player only)~~ - this isn't updated on map change, so is difficult to maintain between character selection etc
- [x] Loot messages
- [x] Dialog messages (examples needed)
- [x] Emotes
- [x] ~~Incoming/outgoing whispers and chat messages~~ Too messy with the friend alias feature
- [x] Party Window
- [x] Bond upkeeps
- [x] ~~Ability to toggle on/off without map change~~ Issues with outpost party window not being refreshed, other side effects
- [x] How to handle chat history? Hook OnPrintChat - NOTE: GWToolbox messages e.g. "Hi <player_name>" can't be caught easily - resolved by making Toolbox Info messages bypass the chat log i.e. disappear on map change
- [x] Hall of Monuments
Owned by: CHARACTER NAME
- [x] Player name in cinematics

**Comment by HasKha** [comment]
Another big one is the name in the main viewport (under each player) and in the target. 

I don't think toggle is as important. Even requiring a client restart might be ok.

**Comment by HiImFlo** [comment]
Customized weapons
Bond upkeeps
Friend list
Guild window

**Comment by takepen** [comment]
Probably district too. If some kiddo is waiting in the outpost for the streamer to report them.

**Comment by 3vcloud** [comment]
Updated with the work so far, and I've given comments against the friend list and district issues

**Comment by HiImFlo** [comment]
@3vcloud 

Wasnt sure whether I was supposed to create a new issue because everything is so neatly collected here.

When entering hall of monuments you see the following un-obfuscated message:

"""
Hall of Monuments
Owned by: CHARACTER NAME
HIGHEST TITLE IN GWAMM TITLE TRACK
""

Would be great if the real character name could be removed there as well.

**Comment by 3vcloud** [comment]
Yep, ta

**Comment by BearsMan** [comment]
> @3vcloud
> 
> Wasnt sure whether I was supposed to create a new issue because everything is so neatly collected here.
> 
> When entering hall of monuments you see the following un-obfuscated message:
> 
> """ Hall of Monuments Owned by: CHARACTER NAME HIGHEST TITLE IN GWAMM TITLE TRACK """
> 
> Would be great if the real character name could be replaced by the obfuscated value there as well.

in other words @HiImFlo means this from my image screen: https://i.imgur.com/Nlezsm4.jpeg

**Comment by BearsMan** [comment]
Should this be closed since Obfuscator is very bugged atm, or should we keep it in case we end up having to fix it one day?

**Comment by BearsMan** [comment]
Should this be closed? Or are we still testing issues with Obfuscator?

**Comment by DubbleClick** [comment]
We will revive it at some point, can stay open.
