### ISSUE TITLE
Completion Window: Skills do not show as complete until you switch to the corresponding 2nd profession.

### ISSUE THREAD

**Issue by oliverpechey** [gwdevhub/GWToolboxpp#664]
Replication Steps:

1.) Log on to a character than has say.. an assassin elite skill unlocked. But you are not an assassin in primary or secondary profession.
2.) Go to the Elite Skills section of the completion window, the skill shows as not complete.
3.) Switch your 2nd profession to Assassin. The skill will then be ticked.

Workaround:

In the skills window, change to every single profession before starting a skill hunting session.

**Comment by 3vcloud** [comment]
Can't do this because we haven't mapped out the location in memory that tells us which professions the character has unlocked. Instead, there is a message that describes this in the hint icon of the skills window
