### ISSUE TITLE
Withdraw all id/salv kits

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#689]
[20:17] John Click: Does the store/withdraw all salvage kits only store/withdraw one for anyone else?

**Comment by minifantom** [comment]
Hey, i've noticed the same with minipets, i guess item need to be stackable

**Comment by 3vcloud** [comment]
That'll be dedicated vs non dedicated

**Comment by minifantom** [comment]
They were all unded and all the same
