### ISSUE TITLE
Hero builds mercenary replacement

### ISSUE THREAD

**Issue by Target6379** [gwdevhub/GWToolboxpp#719]
Hi,

Currently with the way hero build loading works, I have a singular hero team loadout for my melee classes but then need to have multiple per caster due to them having mercenary heroes made after them.

For example, my necro character is my mercenary BiP. This means that I need a specific set of hero team builds just for necro that take Master of Whispers instead of my mercenary. It would be great to be able to set default fallback heroes, assuming the one selected can't be loaded.

Hopefully that makes some sense.

**Comment by 3vcloud** [comment]
You’ve got 2 options here without any code changes:

1. you could set up a team build for every iteration that you need, then add a hotkey for each one. Set the profession of the hotkey to match the build it’s loading and bind them all to the same key. If you press the key as a monk, it’ll load a different bar than if you were on a necro.
2. Don’t rely on mercenaries and instead take the time to unlock and use heroes instead. This way you won’t need to worry about this issue at all.

Fallback heroes have been mentioned before but it’s a lot of extra ifs and buts for something that you can already handle by other means

**Comment by 3vcloud** [comment]
The chat command to load a hero team is ‘/heroteam [name of team build]’

**Comment by DubbleClick** [comment]
There's a third and maybe most sensible option: create your mercenaries and then delete the character. That way you can use the same mercenaries on every character.
