### ISSUE TITLE
Zaishen key issue in last row of expanded bag

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#769]
hazyPixels from Reddit

On the odd chance that you really are a GW dev, there's a bug that popped up with the recent "Superior Rune of Holding" update. If you have copper zcoins in the bottom row of your expanded inventory, you aren't able to exchange them for silver coins until you move them to a higher row.

**Comment by 3vcloud** [comment]
How to fix?
```
// ....
  uint local_e0 [54]; // <--- stack too small!!!! needs to be big enough for potentially all items in inventory.
  uint local_8;

// ....

  DAT_00a30264 = pvVar2; // Inventory ptr
  FUN_00582630();
  puVar7 = &local_e4; // Number of item ids written (ptr)
  local_e4 = 0;
  out_buffer = local_e0;
  uVar8 = 0x36; // <--- size of array in stack (54)
  pvVar2 = (void *)GetPlayerInventory();
  GetItemIdsFromInventory(pvVar2,uVar8,out_buffer,puVar7); // Problem.
  ```

**Comment by adituv** [comment]
Only way I can see to patch it in place would be to increase the stack allocation, and readjust the offsets of every other stack variable.  It's intensive and very brittle, so I think the best way would probably just be to ask ANet to do the fix on their end, if that's possible.

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/6f073adea5eaed6f4b2f5164b65548eb9173c0bc
