### ISSUE TITLE
make more events flash the taskbar icon

### ISSUE THREAD

**Issue by HasKha** [gwdevhub/GWToolboxpp#88]
such as zoning or getting invited to a party

(note to self: getting invited is stoc 444)

* [x] receive a pm
* [x] zoning
* [x] party change
* [x] you get ressed
* [x] someone pings you
* [x] trade alert goes off (#185)
* [x] someone trades you (#185)
* [x] cutscene starts / ends

**Comment by Hour-of-the-Owl** [comment]
someone trading you? maybe only flash when they actually submit the trade, if that's possible

**Comment by HasKha** [comment]
done zoning and getting invited

**Comment by Hour-of-the-Owl** [comment]
what about when a custom message appears in chat? e.g. I want to know if someone says "misty" in AC or something like "urgoz skipway"

**Comment by Hour-of-the-Owl** [comment]
suppress the party invite one when you're not the leader of the party please

**Comment by HasKha** [comment]
-when you get ressed (taken from #150)

**Comment by Hour-of-the-Owl** [comment]
when "I'm targeting/following [YOUR NAME HERE]." appears in team chat - a lot of people don't think to PM to get someone's attention

Is it possible to play a sound as well as flashing? A lot of the time when I'm tabbed out I'm looking away from the computer or watching a video in full-screen.

**Comment by HasKha** [comment]
updated from #185
