### ISSUE TITLE
Add hotkey (chat command) to open pet window

### ISSUE THREAD

**Issue by franneck94** [gwdevhub/GWToolboxpp#907]
A nice feature would be if there is a option to auto open the ranger pet window when entering an explorable.

**Comment by 3vcloud** [comment]
So theres a gw hotkey for this already, but toolbox won't auto trigger the hotkey because the pet commander ui frame (that responds to the key) isn't loaded yet. Might revisit the larger issue of UI not being ready for toolbox hotkeys on map load, but not for this specific feature
