### ISSUE TITLE
UI scale does not update on window resize

### ISSUE THREAD

**Issue by adituv** [gwdevhub/GWToolboxpp#912]
When you resize the guild wars window in windowed mode below a certain point, it automatically overrides your interface scale without Toolbox updating the cached UI scale.  This leads to widgets with "snap to interface" modes not displaying correctly, as in the attached screenshot.

When I placed a trace on OnUIMessage (Resources.cpp L104) it did not trigger from window resizing, so to update the cache on window resize may be an involved change.  An easier workaround would be to force update the scale multiplier in the affected widgets, if the performance isn't too badly affected.

All that said, no-one really plays in a small window any more.  I only noticed when I made a small window to keep an eye on nine rings while working on other things.

![gw018](https://github.com/HasKha/GWToolboxpp/assets/1254246/c5ca4d6c-1e61-45e1-a8f1-ec5bd624dea8)

**Comment by 3vcloud** [comment]
Does bypassing the cache work?

**Comment by adituv** [comment]
> Does bypassing the cache work?

Actually no it does not.  I guess that makes it a reverse engineering effort of finding the current interface size rather than the user's saved preference.
