### ISSUE TITLE
Rare crash issue when triggering hotkeys just before map change

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#942]
Scenario: someone scrolls into uw, you're using your hotkey to swap all 5 armour pieces at once. With good ping, no issue. With bad ping and some unlucky timing, gw crashes.

**Comment by BearsMan** [comment]
I have had the bad ping spike when casting spells, however. I do not believe that could crash the game.

**Comment by 3vcloud** [comment]
@DubbleClick would be good to get some dumps for this if it happens again

**Comment by DubbleClick** [comment]
> @DubbleClick would be good to get some dumps for this if it happens again

No dumps happen there, gane either hangs indefinitely or instantly closes.

**Comment by 3vcloud** [comment]
I’m starting to think we should move the update loop into the render callback instead of the game thread
