### ISSUE TITLE
[Hotkey - Guild Wars Key] Toolbox adds key assignments to seemingly random actions

### ISSUE THREAD

**Issue by HiImFlo** [gwdevhub/GWToolboxpp#972]
Toolbox adds key assignments to seemingly random guild wars keys

Steps to reproduce:
1. Create two hotkeys that trigger a Guild Wars Key (in my case, target self and then let hero 1 use skill 8)
2. Assign both to the same hotkey
3. Press the hotkey a couple of times
4. At some point, sometimes even after the first hotkey usage, your settings are messed up and the hotkey you assigned to your 2 actions is now also assgned to some other random hotkey in the GW settings (F11 > Control, in my case, mostly the target next/previous enemy hotkey)

**Comment by 3vcloud** [comment]
Is your hotkey ticked to block gw, or does gw get the keypress too?

**Comment by HiImFlo** [comment]
GW gets the keypress (the "Block key when..." box is not ticked), but that keypress (in this case Numblock 3) is not assigned to anything other than the two toolbox hotkeys

**Comment by 3vcloud** [comment]
and when num lock isn't on, what is the key?

**Comment by HiImFlo** [comment]
Not quite sure what you mean. When I toggle numlock on/off the key in toolbox settings doesnt change. This is a screenshot with numlock off: 
![grafik](https://github.com/gwdevhub/GWToolboxpp/assets/37843152/5f12afc9-2c87-4f43-a522-ef27e44eea00)

**Comment by 3vcloud** [comment]
Maybe I misunderstood; is your key party of your numpad on your keyboard, and if so does the key have another meaning when your caps lock is off?

**Comment by HiImFlo** [comment]
Ah, I think I see what you mean. My keyboard has a physical numpad (https://www.amazon.de/Logitech-Mechanische-Gaming-Tastatur-Deutsches-Tastaturlayout/dp/B01GHP1IDY), if the numpad is off the meaning of the numpad 4 key is "Left".

That being said, I have assigned most of my hotkeys to numpad keys, and I do not turn off numlock like ever (else I would instantly notice because all my other stuff should stop working as well). In my normal gameplay I would not use the numblock keys themselves but instead my remapped mouse keys or logitech macro keys that then trigger the numblock keys, but for the sake of removing that extra layer of complexity I just did this test with pressing the numblock keys directly.

----------------------------------------------

... and, in addition, maybe related, perhaps another separate issue, and even easier to reproduce: When I press the hotkey (Numblock 4) while targetting an enemy only the first of the 2 is executed and it targets myself, but then the 2nd hotkey does not instantly cause the hero to use its skill, and I have to press the hotkey again.

However, when I am already targetting myself, the hero properly uses his skill right away (checkmark in the heroes skillbar appears/disappears).

![grafik](https://github.com/gwdevhub/GWToolboxpp/assets/37843152/bbfc3719-fde5-4ed6-b49b-04d134f22792)

**Comment by 3vcloud** [comment]
> Toolbox adds key assignments to seemingly random guild wars keys
> 
> Steps to reproduce:
> 
> 1. Create two hotkeys that trigger a Guild Wars Key (in my case, target self and then let hero 1 use skill 8)
> 2. Assign both to the same hotkey
> 3. Press the hotkey a couple of times
> 4. At some point, sometimes even after the first hotkey usage, your settings are messed up and the hotkey you assigned to your 2 actions is now also assgned to some other random hotkey in the GW settings (F11 > Control, in my case, mostly the target next/previous enemy hotkey)

Tested this and can't find any issue with the setup, the only thing I can think of is that your key is already assigned to an action in GW, and its triggering because you're trying to use your Toolbox hotkey when you're not in an explorable area; if the key doesn't match the certeria (i.e. in an explorable area in my example) then it won't block the key, and GW will process the key as whatever it is in the settings

The only timeToolbox changes your GW key mapping is when you load GW settings from a file via "Guild Wars Settings" module, which is done either manually or through a chat command
