### ISSUE TITLE
Hotkey to remove bond(s)

### ISSUE THREAD

**Issue by halogod35** [gwdevhub/GWToolboxpp#974]
I would like to propose a feature request where we can use a hotkey to remove a bond or all maintained enchantments.

For example, if casting Holy Veil on a party member, you can press a hotkey such as Ctrl + Spacebar to remove all maintained bonds or maybe Ctrl + 1-8 to remove bonds the party member of that number.

The idea come from the fact that Guild Wars can fully be played with a keyboard. i.e. a person playing Guild Wars on a laptop without a proper mouse. Currently, bonds can only be removed by double clicking on vanilla Guild Wars or single clicking with the bonds monitor on GWToolbox++.

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/fb32e6c738a0d44bccce27e60159d396912fddfc
