### ISSUE TITLE
Inventory: store all <Item> only moves the clicked one, 

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#977]
![image](https://github.com/gwdevhub/GWToolboxpp/assets/7896469/44386eb9-c78d-4cc4-b940-a96ee651d232)

**Comment by 3vcloud** [comment]
https://github.com/gwdevhub/GWToolboxpp/commit/1529b48ed5fa3867dc6f9510136a631a874f0775

**Comment by SPProgsandCodes** [comment]
Leaving the empty space and add any collaborator
