### ISSUE TITLE
Add Ghost-in-the-Box to default "dont hide"-List if white item drops are disabled

### ISSUE THREAD

**Issue by HiImFlo** [gwdevhub/GWToolboxpp#978]
Steps to reproduce: Drop a Ghost-in-the-Box with default settings after disabling white item drops

![grafik](https://github.com/gwdevhub/GWToolboxpp/assets/37843152/ba6ea492-f927-4abf-afc8-d5b008d5ea22)

Of course you can just add them yourself (which I now did), but as most/all other pcons are added by default it would be great if those were too.

ID: 6368

**Comment by DubbleClick** [comment]
Too cheap imo, no point in excluding it by default. Not to mention that the change wouldn't affect anyone who has already used toolbox.
