### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by yoyorast1** [gwdevhub/GWToolboxpp#981]
The game crashes after playing for like 30 min. 

[crashes.zip](https://github.com/gwdevhub/GWToolboxpp/files/14396164/crashes.zip)

**Comment by adituv** [comment]
Some notes on the crash:

The crash is Armory-related.  It's happening during the UndrawAgentEquipment_Func call in ClearArmorItem.  The item being cleared each time is a chestpiece.  The crash dump has `equip` point to junk data, seemingly in the middle of a unicode string, but I don't know whether that junk data was from the GetPlayerEquipment call or whether it's reading a random different value from a register where `equip` was previously stored.

In case `equip` was originally valid: the class member on `equip` at h0298 (m_componentItem) is an array of 40-byte structures, and UndrawAgentEquipment_Func calls the destructor on the relevant one of them shortly after the assertion "component < arrsize(m_componentItem)".  That destructor then releases four handles owned by that structure, but one of the handles' object pointer is invalid, causing the crash.

**Comment by yoyorast1** [comment]
Crashes stopped once I enabled frame limiter and put it at 60. I was getting crashes regularly with this option disabled.

**Comment by 3vcloud** [comment]
idk how this could happen unless this call was on a different thread to the game thread; the pointer to equip changes between SetArmorItem and ClearArmorItem (if this is true, limiting FPS might have actually helped mask the crash). Chest piece is shing jea raiment, but theres no chest piece item id on the equipment struct thats valid anyway.

@yoyorast1 were you loading into or out of a map at the time? Do you have any other plugins or mods running aside from toolbox when you get the crashes?
