### ISSUE TITLE
Include taking bounty in /dialog take

### ISSUE THREAD

**Issue by Zane1-2** [gwdevhub/GWToolboxpp#984]
Include taking bounty in /dialog take

**Comment by DubbleClick** [comment]
Hmm, bit stupid because dialog id's are different across campaigns.

0x84 for take in eotn, 0x85 for decline (0x1B take icon)
0x85 for take in nf, 0x86 for decline (0x1B take icon)
0x80, 0x81, 0x82 for take kurzick/luxon area (stupid green arrow icon, both for fight and bribe)

**Comment by DubbleClick** [comment]
tempted to just ignore factions and base it off the icon, what do you think @3vcloud ?

**Comment by 3vcloud** [comment]
Icon is fine, but don’t rush it - let’s see if we can sort something out for factions, perhaps look into the dialog npc or something

**Comment by BearsMan** [comment]
Here is the list of the encoded strings from the Kurzick Priest NPC: ```0x108 0x107 0x49 0x27 0x76 0x65 0x20 0x68 0x61 0x64 0x20 0x65 0x6E 0x6F 0x75 0x67 0x68 0x21 0x20 0x28 0x46 0x69 0x67 0x68 0x74 0x2E 0x29 0x1```
 "I've Had Enough! (Fight), 
```0x108 0x107 0x49 0x27 0x6C 0x6C 0x20 0x6D 0x61 0x6B 0x65 0x20 0x69 0x74 0x20 0x77 0x6F 0x72 0x74 0x68 0x20 0x79 0x6F 0x75 0x72 0x20 0x77 0x68 0x69 0x6C 0x65 0x2E 0x20 0x28 0x42 0x72 0x69 0x62 0x65 0x2E 0x29 0x1```
 "I'll make it while your while. (Bribe)", 
```0x108 0x107 0x53 0x6F 0x20 0x62 0x65 0x20 0x69 0x74 0x2E 0x1```
 "So be it."
 ```0x5E92 0x9FFB 0xF999 0x6B63```
 Dialog Body number

**Comment by BearsMan** [comment]
Luxon Priest dialog: Note: I have more Luxon points than Kurzick.
```0x5E9C 0xA43E 0xC5CE 0x166A``` - Dialog Body
```0x5E9F 0xDFDE 0xEBF7 0x790``` - I am interested in Blessings.
```0x2AE5 0xDDC2 0xE736 0xD21``` I'll be on my way.

I have to see when I can do a run to get more Kurzick points for the Fight/Bribe dialogs.
