### ISSUE TITLE
Skillmonitor Widget: cast time indicator doesn't account for half cast times, position is off

### ISSUE THREAD

**Issue by DubbleClick** [gwdevhub/GWToolboxpp#989]
![image](https://github.com/gwdevhub/GWToolboxpp/assets/7896469/b50fc0d9-6e65-4d79-83f7-5474815b18a6)

**Comment by 3vcloud** [comment]
HCT issue sorted, https://github.com/gwdevhub/GWToolboxpp/commit/7ce8c43b646cdf4da5b6900eb44552fef2b90588

**Comment by 3vcloud** [comment]
@DubbleClick can you check the offset issue on dev? I can't replicate it

**Comment by DubbleClick** [comment]
Yep, it happened on dev, but it's not consistent. I wanted to figure it out over the weekend, but didn't find the time.
