### ISSUE TITLE
Nic set collection and completion status indicators

### ISSUE THREAD

**Issue by Wibblepuppy** [gwdevhub/GWToolboxpp#996]
**Problem:** Nic set completion status is not visible in the inventory requiring repeated look ups to check progression.
**Proposal:** A method of indicating that future Nic set items have X of Y collected.
**Suggestions:** (1) Add a numeric to the item in the inventory that reflects the progress of a Nic set accumulation. Multi-account players need more than one set so add a multiplier option for that numeric. (2) A new window that aggregates Nic set item collection and progression and is linked to the cycle. (3) A /chat option to display or warn about Nic set progression for the upcoming X cycles.

**Comment by 3vcloud** [comment]
We'll be implementing an extra line in the hover description to say whether an item is a nick item or not - this combined with the ability to "Withdraw all <item>" in the right click menu, and the fact that we don't want to scan inventory every time you hover a nick item means that you should be able to get along ok without this
