### ISSUE TITLE
Completion window click options that show outstanding characters per location

### ISSUE THREAD

**Issue by Wibblepuppy** [gwdevhub/GWToolboxpp#997]
**Problem:** In the Completion window there is no method to cross-check all characters against a Mission/Vanquish etc, other than scrolling through the character names and eyeballing the required line for the missing ones.
**Proposal:** Introduce a cross-check option against each Mission/Vanquish entry that would summarise the outstanding and missing characters for that entry.
**Suggestion:** A modified click event (say Alt+click) on a Mission/Vanquish would display a summary panel of outstanding characters (the white, unticked ones) and another (say Ctrl+click) summarises characters ineligible to reach that area (the grey ones).

**Comment by 3vcloud** [comment]
This is on hover for next release
