### ISSUE TITLE
Large majority of features not working

### ISSUE THREAD

**Issue by Spectarz** [gwdevhub/GWToolboxpp#999]
after updating the GW game client most of Toolbox features are no longer working.  Also when closing toolbox, it locks up the game.  Cant move character with click, and can't control the camera.  Left click doesn't work in any gw menus. Also it doesn't truly remove toolbox, when trying to reload toolbox it says it is still injected.
  Hotkeys don't work.  Minimap shows up.  Travel doesn't work. etc etc.

**Comment by BearsMan** [comment]
If it ever has a deadlock, do a manual shutdown of the game via Task Manager (at least that is what I did, feel free to ignore that part)
Also, what version of toolbox are you on because older versions are not supported and will crash the game at random times.

**Comment by adituv** [comment]
Last night's game update broke toolbox, yes.  There will be a new toolbox version soon.
